import type { BenchmarkRecord } from './types';

export const benchmarkData: BenchmarkRecord[] = [
  {
    model: 'Llama-3.1-8B-Instruct',
    family: 'Llama',
    paramsB: 8,
    source: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'H100 SXM',
    acceleratorCount: 1,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4 + cuDNN 9',
    precision: 'bf16',
    batchSize: 16,
    contextLength: 4096,
    tokensPerSecond: 590,
    latencyMs: 82,
    vramGb: 18,
    powerW: 330,
    date: '2026-02-21'
  },
  {
    model: 'Llama-3.1-8B-Instruct',
    family: 'Llama',
    paramsB: 8,
    source: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'A100 80GB',
    acceleratorCount: 1,
    runtime: 'TensorRT-LLM',
    runtimeVersion: '0.16.0',
    buildTag: 'CUDA 12.2',
    precision: 'fp16',
    batchSize: 16,
    contextLength: 4096,
    tokensPerSecond: 515,
    latencyMs: 95,
    vramGb: 19,
    powerW: 290,
    date: '2026-02-21'
  },
  {
    model: 'Llama-3.1-8B-Instruct',
    family: 'Llama',
    paramsB: 8,
    source: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    hardwareVendor: 'AMD',
    hardwareSku: 'MI300X',
    acceleratorCount: 1,
    runtime: 'ROCm SGLang',
    runtimeVersion: '0.4.2',
    buildTag: 'ROCm 6.2',
    precision: 'bf16',
    batchSize: 16,
    contextLength: 4096,
    tokensPerSecond: 542,
    latencyMs: 90,
    vramGb: 21,
    powerW: 345,
    date: '2026-02-19'
  },
  {
    model: 'Mistral-7B-Instruct-v0.3',
    family: 'Mistral',
    paramsB: 7,
    source: 'mistralai/Mistral-7B-Instruct-v0.3',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'RTX 4090',
    acceleratorCount: 1,
    runtime: 'llama.cpp',
    runtimeVersion: 'b4260',
    buildTag: 'CUDA 12.4 GGML',
    precision: 'int8',
    batchSize: 8,
    contextLength: 4096,
    tokensPerSecond: 202,
    latencyMs: 180,
    vramGb: 11,
    powerW: 248,
    date: '2026-02-20'
  },
  {
    model: 'Mistral-7B-Instruct-v0.3',
    family: 'Mistral',
    paramsB: 7,
    source: 'mistralai/Mistral-7B-Instruct-v0.3',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'L4',
    acceleratorCount: 1,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4',
    precision: 'fp16',
    batchSize: 8,
    contextLength: 4096,
    tokensPerSecond: 168,
    latencyMs: 210,
    vramGb: 13,
    powerW: 70,
    date: '2026-02-23'
  },
  {
    model: 'Mistral-7B-Instruct-v0.3',
    family: 'Mistral',
    paramsB: 7,
    source: 'mistralai/Mistral-7B-Instruct-v0.3',
    hardwareVendor: 'Apple',
    hardwareSku: 'M3 Max 40-core GPU',
    acceleratorCount: 1,
    runtime: 'MLX',
    runtimeVersion: '0.19.0',
    buildTag: 'macOS 15.3 + Metal',
    precision: 'fp16',
    batchSize: 4,
    contextLength: 8192,
    tokensPerSecond: 132,
    latencyMs: 245,
    vramGb: 10,
    powerW: 48,
    date: '2026-02-22'
  },
  {
    model: 'Qwen2.5-14B-Instruct',
    family: 'Qwen',
    paramsB: 14,
    source: 'Qwen/Qwen2.5-14B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'H100 SXM',
    acceleratorCount: 1,
    runtime: 'TensorRT-LLM',
    runtimeVersion: '0.16.0',
    buildTag: 'CUDA 12.4',
    precision: 'fp8',
    batchSize: 16,
    contextLength: 8192,
    tokensPerSecond: 618,
    latencyMs: 102,
    vramGb: 27,
    powerW: 350,
    date: '2026-02-21'
  },
  {
    model: 'Qwen2.5-14B-Instruct',
    family: 'Qwen',
    paramsB: 14,
    source: 'Qwen/Qwen2.5-14B-Instruct',
    hardwareVendor: 'AMD',
    hardwareSku: 'MI300X',
    acceleratorCount: 1,
    runtime: 'ROCm SGLang',
    runtimeVersion: '0.4.2',
    buildTag: 'ROCm 6.2',
    precision: 'bf16',
    batchSize: 16,
    contextLength: 8192,
    tokensPerSecond: 575,
    latencyMs: 116,
    vramGb: 29,
    powerW: 360,
    date: '2026-02-20'
  },
  {
    model: 'Qwen2.5-14B-Instruct',
    family: 'Qwen',
    paramsB: 14,
    source: 'Qwen/Qwen2.5-14B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'A100 80GB',
    acceleratorCount: 1,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4',
    precision: 'bf16',
    batchSize: 8,
    contextLength: 8192,
    tokensPerSecond: 420,
    latencyMs: 144,
    vramGb: 31,
    powerW: 295,
    date: '2026-02-21'
  },
  {
    model: 'DeepSeek-R1-Distill-Llama-8B',
    family: 'DeepSeek',
    paramsB: 8,
    source: 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'L40S',
    acceleratorCount: 1,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4',
    precision: 'bf16',
    batchSize: 8,
    contextLength: 8192,
    tokensPerSecond: 233,
    latencyMs: 176,
    vramGb: 23,
    powerW: 260,
    date: '2026-02-18'
  },
  {
    model: 'DeepSeek-R1-Distill-Llama-8B',
    family: 'DeepSeek',
    paramsB: 8,
    source: 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
    hardwareVendor: 'AMD',
    hardwareSku: 'MI210',
    acceleratorCount: 1,
    runtime: 'ROCm SGLang',
    runtimeVersion: '0.4.2',
    buildTag: 'ROCm 6.1',
    precision: 'bf16',
    batchSize: 8,
    contextLength: 8192,
    tokensPerSecond: 188,
    latencyMs: 209,
    vramGb: 24,
    powerW: 290,
    date: '2026-02-17'
  },
  {
    model: 'Phi-4-mini-instruct',
    family: 'Phi',
    paramsB: 3.8,
    source: 'microsoft/Phi-4-mini-instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'RTX 4090',
    acceleratorCount: 1,
    runtime: 'ONNX Runtime',
    runtimeVersion: '1.21.0',
    buildTag: 'TensorRT EP',
    precision: 'int8',
    batchSize: 16,
    contextLength: 4096,
    tokensPerSecond: 355,
    latencyMs: 110,
    vramGb: 7,
    powerW: 210,
    date: '2026-02-24'
  },
  {
    model: 'Phi-4-mini-instruct',
    family: 'Phi',
    paramsB: 3.8,
    source: 'microsoft/Phi-4-mini-instruct',
    hardwareVendor: 'Apple',
    hardwareSku: 'M2 Ultra 76-core GPU',
    acceleratorCount: 1,
    runtime: 'MLX',
    runtimeVersion: '0.19.0',
    buildTag: 'macOS 15.3 + Metal',
    precision: 'fp16',
    batchSize: 8,
    contextLength: 4096,
    tokensPerSecond: 166,
    latencyMs: 189,
    vramGb: 8,
    powerW: 55,
    date: '2026-02-22'
  },
  {
    model: 'Llama-3.3-70B-Instruct',
    family: 'Llama',
    paramsB: 70,
    source: 'meta-llama/Llama-3.3-70B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'H100 SXM',
    acceleratorCount: 8,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4 NCCL 2.21',
    precision: 'bf16',
    batchSize: 64,
    contextLength: 8192,
    tokensPerSecond: 4010,
    latencyMs: 190,
    vramGb: 560,
    powerW: 2800,
    date: '2026-02-24'
  },
  {
    model: 'Llama-3.3-70B-Instruct',
    family: 'Llama',
    paramsB: 70,
    source: 'meta-llama/Llama-3.3-70B-Instruct',
    hardwareVendor: 'AMD',
    hardwareSku: 'MI300X',
    acceleratorCount: 8,
    runtime: 'ROCm SGLang',
    runtimeVersion: '0.4.2',
    buildTag: 'ROCm 6.2 RCCL 2.20',
    precision: 'bf16',
    batchSize: 64,
    contextLength: 8192,
    tokensPerSecond: 3620,
    latencyMs: 220,
    vramGb: 640,
    powerW: 2950,
    date: '2026-02-24'
  },
  {
    model: 'Llama-3.3-70B-Instruct',
    family: 'Llama',
    paramsB: 70,
    source: 'meta-llama/Llama-3.3-70B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'A100 80GB',
    acceleratorCount: 8,
    runtime: 'TensorRT-LLM',
    runtimeVersion: '0.16.0',
    buildTag: 'CUDA 12.2 NCCL 2.20',
    precision: 'fp16',
    batchSize: 32,
    contextLength: 4096,
    tokensPerSecond: 2950,
    latencyMs: 255,
    vramGb: 640,
    powerW: 2400,
    date: '2026-02-23'
  },
  {
    model: 'Qwen2.5-72B-Instruct',
    family: 'Qwen',
    paramsB: 72,
    source: 'Qwen/Qwen2.5-72B-Instruct',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'H100 SXM',
    acceleratorCount: 8,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4',
    precision: 'bf16',
    batchSize: 64,
    contextLength: 8192,
    tokensPerSecond: 3525,
    latencyMs: 228,
    vramGb: 620,
    powerW: 2750,
    date: '2026-02-24'
  },
  {
    model: 'Qwen2.5-72B-Instruct',
    family: 'Qwen',
    paramsB: 72,
    source: 'Qwen/Qwen2.5-72B-Instruct',
    hardwareVendor: 'AMD',
    hardwareSku: 'MI300X',
    acceleratorCount: 8,
    runtime: 'ROCm SGLang',
    runtimeVersion: '0.4.2',
    buildTag: 'ROCm 6.2',
    precision: 'bf16',
    batchSize: 64,
    contextLength: 8192,
    tokensPerSecond: 3308,
    latencyMs: 243,
    vramGb: 704,
    powerW: 2920,
    date: '2026-02-24'
  },
  {
    model: 'Gemma-2-9B-it',
    family: 'Gemma',
    paramsB: 9,
    source: 'google/gemma-2-9b-it',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'L4',
    acceleratorCount: 1,
    runtime: 'vLLM',
    runtimeVersion: '0.8.4',
    buildTag: 'CUDA 12.4',
    precision: 'bf16',
    batchSize: 8,
    contextLength: 8192,
    tokensPerSecond: 141,
    latencyMs: 236,
    vramGb: 17,
    powerW: 72,
    date: '2026-02-24'
  },
  {
    model: 'Gemma-2-9B-it',
    family: 'Gemma',
    paramsB: 9,
    source: 'google/gemma-2-9b-it',
    hardwareVendor: 'NVIDIA',
    hardwareSku: 'RTX 4090',
    acceleratorCount: 1,
    runtime: 'TensorRT-LLM',
    runtimeVersion: '0.16.0',
    buildTag: 'CUDA 12.4',
    precision: 'fp16',
    batchSize: 16,
    contextLength: 8192,
    tokensPerSecond: 284,
    latencyMs: 160,
    vramGb: 15,
    powerW: 260,
    date: '2026-02-24'
  }
];
